/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNIDemo */

#ifndef _Included_JNIDemo
#define _Included_JNIDemo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JNIDemo
 * Method:    printText
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_JNIDemo_printText
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
